#title: AVERtek # your name photo (or website title) here
logo1: "images/BAHAY-LOGO-leaf-green-gold.png? raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h1 style="color:#A28D5B;"><p style="text-align:center;"><b>MEANS HOME</h1></b></p>
  <br>
  <h2 style="text-align: center;" markdown="1"><b>2MI FROM STADIUM</b><a href="https://www.mlb.com/dodgers/schedule/2021-03" onclick="getOutboundLink('https://www.mlb.com/dodgers/schedule/2021-03'); return false;"<b> DODGERS SCHEDULE</h2></b></a> 
  <br><br> 
  <h2 style="text-align: center;" markdown="1"><b>AFFORDABLE</b><a href="https://alexanbahay.com/gallery/apartment-tours/" onclick="getOutboundLink('https://alexanbahay.com/gallery/apartment-tours/'); return false;"<b> LUXURY</b><h/2></a>
  <br><br>
  <h2 style="text-align: center;" markdown="1"><b>TOUR WITH</b><a href="https://youtu.be/F5zBN4X2BzM" onclick="getOutboundLink('https://youtu.be/F5zBN4X2BzM'); return false;"<b> LOIDA VELASQUEZ</b></h2></a>
  <br><br>
  <h2 style="text-align: center;" markdown="1"><b>VIEW</b><a href="https://alexanbahay.com/gallery/video/?utm_source=AVERtek&utm_medium=AR" onclick="getOutboundLink('https://alexanbahay.com/gallery/video/?utm_source=AVERtek&utm_medium=AR'); return false;"<b> LA LIVING</b></h2></a>
  <br><br>
  <h2 style="text-align: center;" markdown="1"><b>EXPERIENCE</b><a href="https://avertek.github.io/Alexan-Bahay-1Bd/" onclick="getOutboundLink('https://avertek.github.io/Alexan-Bahay-1Bd/'); return false;"<b> 3D/AR FLOORPLAN</b></h2></a> 
  <br><br>
  <h2 style="text-align: center;" markdown="1"><b>AUTHENTIC:</b><a href="https://avertek.github.io/Alexan-Bahay-1Bd/" onclick="getOutboundLink('https://avertek.github.io/Alexan-Bahay-1Bd/'); return false;"<b> LA LIVING</b></h2></a> 
  <br><br>
  <h2 style="text-align: center;" markdown="1"><b>TAKE TOUR; FREE GIFT:</b><a href="https://alexanbahay.com/special/?utm_source=AVERtek&utm_medium=AR" onclick="getOutboundLink('https://alexanbahay.com/special/?utm_source=AVERtek&utm_medium=AR'); return false;"<b> USE CODE: DODGERS</b></h2></a> 
  <br><br>
theme: jekyll-theme-minimal
# Google Analytics
google_analytics: UA-188164724-1 
