#title: AVERtek # your name photo (or website title) here
logo1: "images/BAHAY-LOGO-leaf-green-gold.png? raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h2><b>CELEBRATES THE WORLD CHAMPION DODGERS</h2></b>
  <h2><a href="https://contest.avertek.net/139549" onclick="getOutboundLink('https://contest.avertek.net/139549'); return false;"><b>ENTER FREE CONTEST!</h2></b></a> 
  <br><br>
  <h2><a href="http://bit.ly/DodgerGearAB" onclick="getOutboundLink('http://bit.ly/DodgerGearAB'); return false;"<b> GEAR UP</b><h2></a>
  <br><br> 
  <h3><b>CATCH A GAME:</h3></b><a href="https://www.mlb.com/dodgers/schedule/2021-03" onclick="getOutboundLink('https://www.mlb.com/dodgers/schedule/2021-03'); return false;"</b><b> 2021 SCHEDULE</b></a>
  <br><br>
  <h3><b>BUY DODGERS TICKETS:</h3></b><a href="https://www.mlb.com/dodgers/tickets" onclick="getOutboundLink('https://www.mlb.com/dodgers/tickets'); return false;"</b><b> QUICK & EASY</b></a>
  <br><br>
  <h3><b>EXPLORE AUTHENTIC LA LIVING:</h3></b><a href="https://alexanbahay.com/gallery/video/?utm_source=AVERtek&utm_medium=AR" onclick="getOutboundLink('https://alexanbahay.com/gallery/video/?utm_source=AVERtek&utm_medium=AR'); return false;"</b><b> ALEXAN BAHAY MEANDS HOME</b></a> 
  <br><br>
  <h3><b>SLIDE INTO HOME:</h3></b><a href="https://alexanbahay.com/special/?utm_source=AVERtek&utm_medium=AR" onclick="getOutboundLink('https://alexanbahay.com/special/?utm_source=AVERtek&utm_medium=AR'); return false;"</b> <b> TOUR & FREE GIFT, USE CODE: DODGERS</a> 
  <br><br>
theme: jekyll-theme-minimal
# Google Analytics
google_analytics: UA-188164724-1 
